default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  host: localhost
  database: furima_39600_development

test:
  <<: *default
  host: localhost
  database: furima_39600_test

production:
  <<: *default
  adapter: postgresql
  host: <%= ENV["DATABASE_HOST"] %>
  database: furima_39600_production
  username: furima_39600
  password: <%= ENV["FURIMA_39600_DATABASE_PASSWORD"] %>
